name: CI

on:
  push:
    branches:
      - main

jobs:
  test-dotfiles:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      # - name: Install packages
      #   run: brew bundle install
      #   continue-on-error: true
      - name: List all files
        run: ls -la
      # - name: Bootstrap
      #   run: |
      #     if [ -f bootstrap.sh ]; then
      #       chmod +x bootstrap.sh
      #       ./bootstrap.sh
      #     fi
