name: CI

on:
  push:
  schedule:
    - cron: '15 0 * * *' 

jobs:
  test-dotfiles:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      - name: Bootstrap
        run: |
          if [ -f bootstrap.sh ]; then
            chmod +x bootstrap.sh
            ./bootstrap.sh
          fi